### ISSUE TITLE
Protect access to the app

### ISSUE THREAD

**Issue by shouryan01** [Google-Developer-Student-Club-Dearborn/hd2-app#20]
We need to protect access to the app. 

So what the workflow would look like is:

1. The user registers from the website
2. We generate a unique 4 digit code which is sent to the user based on their entered .edu email address
3. The user will then download the app, and will enter the emailed code in the app, [in this interface](https://pub.dev/packages/pinput) or this one but it's not [as good](https://pub.dev/packages/flutter_screen_lock).
4. If the code is correct, the user is allowed to enter the app and the appropriate user info is fetched and rendered (the qr code, user name, etc)
5. For now assume that the code is fetching properly and for testing assume the code is 1234

Again, make everything modular and break everything up into as small files as possible, keep all the auth files in it's own folder if possible.

[If this proves to be too challenging, we will create a simple sign up form like this:](https://github.com/NearHuscarl/flutter_login), which as better animations tbh

**Comment by alielzei** [comment]
I have a feeling 4 digits in this use case isnt a good idea. Usually you enter a code after you enter an email first (claiming who you are). But if you haven't entered an email or any identifying information first then you can try any 4 digit combination. Also codes need to have a short expiry time.

**Comment by shouryan01** [comment]
That's a good point. Perhaps sticking to emails would be a better route after all. We'd need to figure out a way to only authenticate those users whose emails we already have.

I thought of doing things this way because we don't want people to be downloading the app on their own if they're not on the guest list.

**Comment by alielzei** [comment]
We can send a link to the app in the email. And then tell them to go back to the email and press on a link or something. Or let them sign in using the same credentials they signed in with in the website. Then they can complete their registration on the app.

**Comment by shouryan01** [comment]
We can also allow access to the first two screens, and force sign in only for the qr code. Idk if that's clunkier or not, what do you think?

**Comment by alielzei** [comment]
I like the idea. If user == null => show please sign in message. But the main issue was what data to ask from the user in order to let them in. Do you want to do sign in with google? Umich emails are compatible with google sign in but users from other unis might not have that. Not sure if thats easy to figure out tho.

If not this is one possible scenario:

Step 1. Register on website using email only.

Step 2. Receive email with Link to playstore and appstore link.

Step 3. User opens app and it asks them for email.

Step 4. Email is received with the verification code you were talking but 6 digits is more common practice.

Step 5. User puts in email and carries on with completing user data.

Also if user already has app downloaded we can let them start with Step 3 directly.
